name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Copy env.example to .env
        run: cp .env.example .env

      
      - name: List installed node modules
        run: ls -R node_modules/vue-i18n/dist

      - name: Build only
        run: NODE_OPTIONS="--max-old-space-size=8192" npm run build-only
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start