name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      - name: Install vue-i18n 
        run: npm install vue-i18n

      - name: Debug installed packages
        run: npm list
      # and run all Cypress tests
      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

